# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-16 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origine', models.CharField(max_length=200)),
                ('type_asso', models.CharField(max_length=200)),
                ('sous_type_asso', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='fichiers',
        ),
    ]
